; PlatformIO Project Configuration File for ESP32 Ultrafiltration Module
; Optimizado para máxima velocidad de compilación incremental y partición Huge APP (3MB)

[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv

; Opciones de optimización de compilador C++ (Multiproceso y optimización de velocidad)
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -O2
